### PR TITLE
Fix emoji tab selector

### PR DESCRIPTION
**Pull request by swba**
Emoji type tab switching doesn't work properly if there is another element in the DOM with `.active` class, because active tab was selected by just
```
let tab = document.querySelector('.active');
```
I made selector more specific:
```
let tab = document.querySelector('#emoji-palette .emoji-tab.active');
```

### CODE REVIEW

**Comment by swba** [comment]
One more fix. When editor is placed inside an absolutely or relatively positioned container, `#emoji-close-div` can not work as can appear to be under the whole container. Thus it's better to append it not to `body`:
```
document.getElementsByTagName('body')[0].appendChild(closeDiv);
```
but to Quill container:
```
quill.container.appendChild(closeDiv);
```

**Comment by nsobolev** [comment]
Hey.

Can the class do better  - .emoji-tab-active ? Cascade is not the best idea.

**Comment by maxtsh** [comment]
this fix should be merged to master.
thanks man you saved me a lot of time. @swba

**Comment by ShmatkoAndrey** [comment]
Are you planning to release it?

**Pull request merged**
