### PR TITLE
Improve emoji panel positioning

### PR DESCRIPTION
**Pull request by NidhiT14**
Partial solution to quill-emoji panel positioning.
Issues:
https://github.com/contentco/quill-emoji/issues/46
https://github.com/contentco/quill-emoji/issues/71
https://github.com/contentco/quill-emoji/issues/76

### CODE REVIEW

**Comment by KeithGillette** [comment]
Hi @yeminhtut & @himynameistimli — Any thoughts on this PR? We've experienced the quill-emoji panel responsive positioning problems noted in the referenced issues. Any improvement in the automatic positioning of the panel would be greatly appreciated.

**Comment by jnarowski** [comment]
@KeithGillette not sure if this is active, should we fork and start pushing to another repo?

**Comment by jnarowski** [comment]
and @NidhiT14

**Comment by KeithGillette** [comment]
Hi @jnarowski — @NidhiT14  & I were hoping that the maintainers would consider a PR so we wouldn't have to maintain a fork. @himynameistimli has merged dependency updates as recently as this February, so it looked like the repository was still active, but there hasn't been a new release in more than a year, so perhaps not.

We'd switch our project to an actively maintained fork that incorporated this PR and would continue to contribute if we generated more enhancements.

**Pull request merged**
